### PR TITLE
Add toggle to turn on clickable links in PDFs:

### PR DESCRIPTION
**Pull request by burke**
These links open in the default browser. There are a few limitations:

* The annotation data we get from pdf.js only has the maximum outer bounding rectangle for each link. When links span two lines, this means we get a single rectangle enclosing both lines, rather than two rectangles; one for each portion.
* Since these links are shown in a separate layer above the canvas, they kind of mess with selection when the cursor is over them. I've made the link display toggle-able for this reason.

Also I don't write a lot of JavaScript and I didn't really factor this code well. Happy to revise if this is something you’d consider merging.

### CODE REVIEW

**Comment by fonol** [comment]
Hey thanks a lot, that is by far the biggest pull request I got up to now.
The layer stuff above the canvas gave me a lot of headache too, especially when doing the highlighting.

> Also I don't write a lot of JavaScript and I didn't really factor this code well. Happy to revise if this is something you’d consider merging.
Neither me so no worries :-).
I will do some testing, and then upload the updated version.

**Comment by fonol** [comment]
I did two very small changes:
1. The icon for the toggle button is a font-awesome icon now. I started using these maybe one or two months ago since the markdown editor library uses fontawesome 4.7 anyway. I just haven't replaced all the old custom SVGs yet.

2. The annotation layer is only fetched if `pdfLinksEnabled` is true. If you toggle the variable, the current page is rerendered.

Develop and master should now be on the same state with your changes included.

**Comment by burke** [comment]
Excellent, thanks! I'm really happy with this plugin so far. There are a few things that don't feel quite as easy as I want them to, or where I run into just a little bit more friction than I want for the workflow I'm trying to make work, but I think I can probably fix these too. Great work on this!

**Comment by fonol** [comment]
Thanks. Feel free to message me if you have any specific ideas or plans, I also got a lot of things on my list, so we can exchange ideas before! If you got any questions about the codebase, please ask. This project has basically wildly grown from just "full-text search in the add window" into any direction I was interested in at that specific moment, and a lot of features were just spontaneously added. The codebase kind of reflects that ;-)

**Pull request merged**
