### PR TITLE
Compatibility with 2.1.24

### PR DESCRIPTION
**Pull request by Arthur-Milchior**
Hi,

I'm a beta tester of anki 2.1.24. And I'm sorry to let you know that your add-on is not compatible anymore, due to recent changes in anki.
In this case, the changes are mostly syntactic. So easy to make. Please see the commits to see the reason of those change.
Actually, the code I send you should even be compatible with older version of anki, since .all, .scalar and .first have been in anki for a long time, and so are find_cards, find_notes

### CODE REVIEW

**Comment by fonol** [comment]
Hi, thanks for the info and the code, but except for a small issue, the develop branch is already adapted to the changes :). I just wait for the release of 2.1.24, and then do a new release, where I set the min version to 2.1.24. Stuff related to tags is still broken, but will work again when the `assert `mentioned in https://anki.tenderapp.com/discussions/beta-testing/1868-anki-2124-beta will be removed.

**Comment by Arthur-Milchior** [comment]
For your information, you can already release the 2.1.24 code without affecting any user on smaller version.
You just need to go on ankiweb, states that the current version goes up to 2.1.23, submit. Then when you edit again the add-on, you'll see a button which allows you to upload the 2.1.24 version.

This would allow beta tester to test your code already.

May I suggest also adding this kind of information in a file DEVELOPPER.md or something like that, so other devs know where to get informations about the development process as soon as they clone the repo.
I must admit that I don't see other add-on dev using multiple branch, so I didn't thought about checking here. My bad

**Comment by fonol** [comment]
Hi, that is a good idea, but not possible currently. 2.1.24 is not out yet, so there is no button that allows to select it as the supported version.
I might add a help file for the code, or edit the repo wiki when I find time.

**Comment by Arthur-Milchior** [comment]
I assure you that you can do it. Actually, I already have add-ons for 2.1.24
For example, look at advanced browser https://ankiweb.net/shared/info/874215009
It has a version for 2.1.24 and a version for older anki. (Not my add-on, I'm only a contributor here)
And anyway, there is no "button" to select the version. You need to enter the number yourself

**Comment by Arthur-Milchior** [comment]
To be clear, you need to enter the number "-23" on the current add-on, to state that it does not work after anki 23. This will ensure that beta tester can't download it right now. It's only after you did that and save this change that you'll be able to add a new version

**Comment by fonol** [comment]
My bad, I should have read the small text directly beneath the version input.
Still unsure if I should upload the develop branch, as it is kinda bad to use right now (inputting tags throws an error if `searchOnTagEntry` is enabled, which it is by default, same goes for clicking on tags).

**Comment by Arthur-Milchior** [comment]
I at least suggest you put a limit on current version to -23. So when Damien put 24 online, people will just see it stopping to work instead of receiving error messages which can' be understood. But that's mostly a matter of opinion at this point

**Comment by fonol** [comment]
Totally reasonable, done.

**Comment by An-png** [comment]
Is this still an issue? Some features now require anki 2.1.24beta3+ in order to work.

**Comment by Arthur-Milchior** [comment]
I may check eventually whether it is still an issue. I have little time right now and do not really recall what was the error

**Pull request closed without merging**
