### PR TITLE
Work in progress: tidying up dialogs, moving stuff

### PR DESCRIPTION
**Pull request by p4nix**
Not ready for deployment, but still wanted to start pull request. I am not sure when I can add the reminding stuff right now. Perhaps merge into another branch?

- when note was opened, and Create dialog is opened from SIAC menubar (or the according shortcut), the note gets prefilled with the current note's details (tag, priority)
- added option to jump back to reviews on review interruption (when Done! is pressed), also closes AddDialog (after loading new note, not optimal, wip)
- added external link icon for external files in the search pane
- added shortcut for page snapshot + page extract (the former one being requested from a user in medschool, would be nice if we could add this quite soon)
- moved tag chooser to a separate dialog, priority queue still to be done

image

### CODE REVIEW

**Comment by fonol** [comment]
Nice, thanks. If you haven't already started, I could do the priority/schedule widget.
I would like it most to have the slider still in the create tab (like before or after the tag entry), and to move the specific schedule to its own tab.

**Comment by p4nix** [comment]
I haven't started, so I'd be fine with you moving it :P But leaving the priority slider still accessible in the Editor would have been my idea as well. But it'd still be nice to be able to open the Priority dialog with the relation to the other files. And for the scheduling, it'd be nice if the same dialog as in the done dialog would be used - because I'm still imagining one cool change (we still got to talk about that one, but later), and having it all in one place would be kind of nice.

**Comment by fonol** [comment]
> But it'd still be nice to be able to open the Priority dialog with the relation to the other files.

Sorry, can't follow, what do you mean by other files? If you mean that there still should be a priority dialog with slider and special schedule widget combined, that will definitely stay that way as it is used in the reading modal.

> And for the scheduling, it'd be nice if the same dialog as in the done dialog would be used

I don't know about your idea, but if I don't misread you, you propose to have the schedule widget in its own dialog instead of a tab? I think the general approach should be to have the slider and schedule as independent flexible widgets, and the dialogs should just pick what they need, so you already have the stuff in one place (`components.py`).

**Comment by p4nix** [comment]
Just a side-note, could you look into the possibility of adding MathJax functionality to the card rendering in the searches? Would be quite nice to see the formulas. I just tried adding the mathjax.js, but apparently there is more to it.

**Comment by fonol** [comment]
> Just a side-note, could you look into the possibility of adding MathJax functionality to the card rendering in the searches? Would be quite nice to see the formulas. I just tried adding the mathjax.js, but apparently there is more to it.

It is possible and in principle really quick to do (just include the script, and after each call to `setSearchResults`, call `MathJax.typeset()`), but I would like to take some time to test the Markdown / Mathjax interplay. Might be that there are some issues or not. But that's why this is a change I wouldn't want to rush. But yeah, it has been on my list basically since the beginning of the add-on, but in fact, I hadn't thought about it for quite some time until you just mentioned it.

image

**Pull request merged**
